function ds_print_summary(results, filters, cfg, show_coefficients)
%DS_PRINT_SUMMARY Print one requirements-driven simulation result.

fprintf(['\nNyquist rate %.0f Hz: bandwidth %.1f Hz, OSR %.2f, ' ...
         'modulator clock %.0f Hz\n'], ...
    results.nyquist_rate_Hz, results.bandwidth_Hz, ...
    results.OSR, results.Fs);
fprintf('Input %.1f dBFS; coherent tone %.3f Hz at FFT bin %d\n', ...
    results.input_level_dBFS, results.tone_Hz, results.tone_bin);
if results.input_noise_enabled
    fprintf('Input-noise density %.3f nFS/sqrt(Hz), seed %d\n', ...
        1e9*results.input_noise_density_FS_per_sqrt_Hz, ...
        cfg.analog.input_noise_seed);
end
fprintf('Nominal %d-bit output; target ENOB range %.1f to %.1f bits\n', ...
    results.output_word_length_bits, cfg.spec.minimum_target_enob, ...
    cfg.spec.maximum_target_enob);

fprintf(['Filter response at %.1f Hz: A = %.3f dB, B = %.3f dB; ' ...
         '0..%.1f Hz droop: A = %.3f dB, B = %.3f dB\n'], ...
    cfg.signal.tone_Hz, results.gain_at_tone_dB(1), ...
    results.gain_at_tone_dB(2), cfg.signal.bandwidth_Hz, ...
    results.passband_droop_dB(1), results.passband_droop_dB(2));

fprintf(['Quantized Filter B (Q1.%d): tone gain %.3f dB, ' ...
         'droop %.3f dB, attenuation at %.1f Hz %.1f dB, ' ...
         'worst relevant stopband %.1f dB\n'], ...
    results.FIR_coefficient_fractional_bits, ...
    results.quantized_gain_at_tone_dB, ...
    results.quantized_passband_droop_dB, ...
    filters.B.stopband_start_Hz, results.quantized_atten_at_Fstop_dB, ...
    results.quantized_worst_stopband_atten_dB);

summary_table = table( ...
    string(results.architecture_labels(:)), ...
    results.enob_A(:), results.enob_B(:), ...
    'VariableNames', {'Architecture', 'FilterA_Measured_ENOB', ...
    'FilterB_Measured_ENOB'});
disp(summary_table);

mash = results.by_architecture.mash_2_1.filter_B;
fprintf(['Selected MASH 2-1 with Filter B: in-band SINAD %.3f dB, ' ...
         'measured ENOB %.3f; FIR order %d\n'], ...
    mash.inband_sinad_dB, mash.measured_enob, results.FIR_order);

integer_filter = results.integer_filter;
integer_performance = results.by_architecture.mash_2_1.filter_B_integer;
fprintf(['Integer reference: input %d bits, CIC %d bits, FIR accumulator ' ...
         '%d bits; ENOB %.3f\n'], ...
    integer_filter.input_width, integer_filter.cic_width, ...
    integer_filter.fir_accumulator_width, ...
    integer_performance.measured_enob);

if show_coefficients
    fprintf('\nFIR order %d: %d coefficients for Verilog (signed Q1.%d)\n', ...
        results.FIR_order, numel(results.FIR_coefficients), ...
        results.FIR_coefficient_fractional_bits);
    disp(results.FIR_coefficient_table);
end
end
